# Generated by Django 5.0.6 on 2024-10-03 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('senha', models.CharField(max_length=10)),
                ('mensagens', models.TextField()),
                ('mensagem_data', models.DateTimeField(default=datetime.datetime(2024, 10, 3, 16, 49, 9, 636195))),
            ],
        ),
    ]
