# Generated by Django 5.0.6 on 2024-10-03 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='mensagem_data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 3, 17, 2, 37, 241336), null=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='mensagens',
            field=models.TextField(blank=True, null=True),
        ),
    ]
